/**
 * FileForge Backend Services API Wrapper
 * This module is kept modular to facilitate future server-side connections (e.g. Node.js or Python).
 */

export interface BackendConversionResponse {
  blob: Blob;
  outputName: string;
  outputType: string;
}

/**
 * Simulates calling the backend converter for complex file types (e.g. PDF to Text/HTML/DOCX).
 */
export async function convertPdfViaBackend(
  file: File,
  targetFormat: string
): Promise<BackendConversionResponse> {
  // Simulate network latency (2 seconds)
  await new Promise((resolve) => setTimeout(resolve, 2000));

  const baseName = file.name.substring(0, file.name.lastIndexOf('.'));

  if (targetFormat === 'txt') {
    const text = `--- FileForge Cloud PDF Conversion Tool ---
Document: ${file.name}
Size: ${(file.size / 1024).toFixed(1)} KB
Processed at: ${new Date().toLocaleString()}

[FileForge PDF Text Extraction Engine]
Successfully extracted text content from "${file.name}".
Your privacy-first server-side integration successfully completed the OCR.
This is a mock conversion output. In production, your backend endpoint will receive the PDF file and return the extracted TXT document.`;
    
    return {
      blob: new Blob([text], { type: 'text/plain' }),
      outputName: `${baseName}.txt`,
      outputType: 'text/plain',
    };
  }

  if (targetFormat === 'html') {
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Converted PDF: ${baseName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 40px; background: #f8fafc; color: #1e293b; max-width: 800px; margin: 0 auto; }
    .card { background: white; padding: 30px; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -2px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }
    h1 { color: #0ea5e9; font-size: 24px; font-weight: 700; margin-bottom: 20px; }
    p { font-size: 14px; line-height: 1.6; color: #475569; }
    .badge { inline-flex: ; display: inline-flex; align-items: center; padding: 4px 10px; border-radius: 9999px; font-size: 12px; font-weight: 600; bg: #e0f2fe; background-color: #e0f2fe; color: #0369a1; }
  </style>
</head>
<body>
  <div class="card">
    <span class="badge">FileForge Server Processed</span>
    <h1>Converted Document: ${baseName}</h1>
    <p><strong>Original File:</strong> ${file.name}</p>
    <p><strong>Size:</strong> ${(file.size / 1024).toFixed(1)} KB</p>
    <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
    <p>This is a simulated PDF-to-HTML conversion. In production, this output is generated by your server using Python/Node.js libraries (e.g., PyMuPDF, pdfplumber, or pdf2image) and returned as a styled page.</p>
  </div>
</body>
</html>`;

    return {
      blob: new Blob([html], { type: 'text/html' }),
      outputName: `${baseName}.html`,
      outputType: 'text/html',
    };
  }

  if (targetFormat === 'md') {
    const mdText = `# Converted Document: ${baseName}

- **Original File:** ${file.name}
- **Size:** ${(file.size / 1024).toFixed(1)} KB
- **Processed Via:** FileForge Modular Backend Server
- **Timestamp:** ${new Date().toLocaleString()}

---

### Document Content Summary
This is a simulated PDF-to-Markdown conversion. 

In production, your backend service (using Python libraries like \`pdfplumber\` or \`marker\`, or a Node.js library) will parse structural layouts and return clean Markdown elements including headers, lists, and bold text.

#### Features of PDF to Markdown:
1. Keeps headers and subheaders organized
2. Converts table grids to markdown tables
3. Keeps lists and lists indices intact`;

    return {
      blob: new Blob([mdText], { type: 'text/markdown' }),
      outputName: `${baseName}.md`,
      outputType: 'text/markdown',
    };
  }

  if (targetFormat === 'docx') {
    // Generate a simple DOCX structured-like text mock file
    const docxText = `FileForge DOCX Conversion File\nSource: ${file.name}\nTimestamp: ${new Date().toISOString()}\n\n[FileForge OCR & Conversion System Output]`;
    
    return {
      blob: new Blob([docxText], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }),
      outputName: `${baseName}.docx`,
      outputType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    };
  }

  throw new Error(`Unsupported backend conversion format: "${targetFormat}"`);
}
